# use terminal command :
# docker-compose -f 'docker-compose-prod.yml' up --build
# docker-compose -f 'docker-compose-prod.yml' down

version: "3"
services:
  front-ytalo:
    build:
      context: .
      dockerfile: DockerFile.prod
    ports:
      - "3010:3010"
    command: >
      sh -c "npm run build \
              npm run start"
    environment:
      PORT: 3010
    # restart: always
