version: "3"
services:
  front-ytalo:
    build:
      context: .
      dockerfile: DockerFile.dev
    ports:
      - "3010:3010"
    command: >
      sh -c "npm install \
             npm run dev" 
    # restart: always
    environment:
      PORT: 3010
    volumes:
      - .:/home/node/app
  